// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-F46p6z1krEQYYILej5ncgvVN3I4HC4',
    appId: '1:981743767532:web:9dbbb49bf1d3d8d506fac9',
    messagingSenderId: '981743767532',
    projectId: 'grocery-6b972',
    authDomain: 'grocery-6b972.firebaseapp.com',
    storageBucket: 'grocery-6b972.appspot.com',
    measurementId: 'G-VE41MS0C6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaslk-oZG19yRgEunUwr5E4_X0r-4zkz0',
    appId: '1:981743767532:android:0df800c0773a7feb06fac9',
    messagingSenderId: '981743767532',
    projectId: 'grocery-6b972',
    storageBucket: 'grocery-6b972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkDNvw0VBv8HUM3wy7Chq_aiqKYErsSWg',
    appId: '1:981743767532:ios:bea4bcf59e634f1306fac9',
    messagingSenderId: '981743767532',
    projectId: 'grocery-6b972',
    storageBucket: 'grocery-6b972.appspot.com',
    iosClientId: '981743767532-ilrfdg8a3ug237hv7hfj88j5c5mnah58.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkDNvw0VBv8HUM3wy7Chq_aiqKYErsSWg',
    appId: '1:981743767532:ios:bea4bcf59e634f1306fac9',
    messagingSenderId: '981743767532',
    projectId: 'grocery-6b972',
    storageBucket: 'grocery-6b972.appspot.com',
    iosClientId: '981743767532-ilrfdg8a3ug237hv7hfj88j5c5mnah58.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocery',
  );
}
